---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "__CHART__.fullname" . }}
  labels:
    app: {{ template "__CHART__.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.deployment.image.tag }}
    app.kubernetes.io/name: {{ template "__CHART__.fullname" . }}
    app.kubernetes.io/component: app
    app.kubernetes.io/managed-by: helm
    {{- if .Values.serviceaccount.labels }}
    labels: {{- toYaml .Values.serviceaccount.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.deployment.podLabels }}
  annotations: {{- toYaml .Values.serviceaccount.annotations | nindent 4 }}
  {{- end }}
---