name: aws-iam-authenticator-sso-wrapper
description: aws-iam-authenticator-sso-wrapper Chart
apiVersion: v2
appVersion: v0.0.15
version: v0.0.18
home: https://github.com/justinas-b/aws-iam-authenticator-sso-wrapper
maintainers:
  - name: justinas-b
    email: 12399634+justinas-b@users.noreply.github.com
