---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: {{ .Chart.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.deployment.image.tag }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: app
    app.kubernetes.io/managed-by: helm
  name: {{ .Chart.Name }}
  annotations:
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.deployment.podAnnotations }}
      annotations: {{- toYaml .Values.deployment.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.deployment.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          {{- if .Values.deployment.image.pullPolicy }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy | quote }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
          command: ["./{{ .Chart.Name }}"]
          args:
            {{- range .Values.deployment.applicationArguments }}
            - {{ . }}
            {{- end }}
          
          {{- with .Values.deployment.resources  }}
          resources:
              {{- toYaml . | nindent 12 }}
          {{- end }}
---
